### ISSUE TITLE
Problem in downloading files

### ISSUE THREAD

**Issue by amirnegah** [mimshins/figma-backup#18] opened 2023-02-27 09:27 UTC
Hello Dear Mostafa

I tried your code to back up our projects in figma.
After starting and logging in to figma, It showed the bot downloading files and showed me a green message.
<img width="928" alt="Screenshot 2023-02-27 at 2 14 30 AM" src="https://user-images.githubusercontent.com/77375918/221524513-4e00c041-9dd6-4990-898d-a94eddb86704.png">

<img width="938" alt="Screenshot 2023-02-27 at 2 14 15 AM" src="https://user-images.githubusercontent.com/77375918/221524580-31b28537-6bb6-4390-b827-3c5cb1140580.png">

But when it's done, in figma-root-backup dir, I couldn't find files. I have 14 files in our figma space but the bot just backup 5 files.

<img width="883" alt="Screenshot 2023-02-27 at 2 14 56 AM" src="https://user-images.githubusercontent.com/77375918/221525084-4a9c0ae1-46f4-416f-a929-2d4737d8b901.png">

Could you help me in this case, please?
If you need more details, just let me know.
Thanks

**Comment by mimshins** [comment] 2023-02-28 20:55
Hello there,
Can you give me the size of your largest file you plan to back up?

We had known issues with large files. Also, with the new approach (waiting for network idleness), we may have aggravated the problem.

**Comment by amirnegah** [comment] 2023-03-02 20:29
> Hello there, Can you give me the size of your largest file you plan to back up?
> 
> We had known issues with large files. Also, with the new approach (waiting for network idleness), we may have aggravated the problem.

Thanks for your answer. It's up to 300MB and when I want do download it with Figma website, It gives me a zip file instead of .fig or .jam file.

**Comment by mimshins** [comment] 2023-03-05 15:56
Thanks for your feedback,
I will investigate further on this issue.

**Comment by StevenDark** [comment] 2023-03-06 10:04
Hi @mimshins I am also having the same issue, when i run this in interactive mode it gives a error on the file download. I've tried manually and get no errors.

**Comment by Netoen** [comment] 2023-06-20 06:00
Hello @mimshins!
Any movement on this one? We also have issue as described above.
In our case, I think, it could be associated with non-english characters (name of the original file in Figma) being stored on disk when you rename the download placeholder.
To be fair, I can see files even as big as 2.6 GB successfully downloaded.
As a bonus, for some reason, some files are saved right in the root, not in the destination directory inside `figma-backup-root/backups/XYZ`.
edit: ran using advised dockerfile, one volume attached in place of `figma-backup-root`
edit2: seems like the issue is also reproduceable if original name has special characters in its name, like `✳️`

**Comment by mimshins** [comment] 2024-06-18 21:53
Closing the issue due to the project being archived.

**Closed as completed by mimshins** 2024-06-18 21:53 UTC
Labels: bug, help wanted, needs-further-investigation
