### ISSUE TITLE
Downloading big files causes crashes

### ISSUE THREAD

**Issue by IgorLeSouverain** [mimshins/figma-backup#17] opened 2022-12-28 09:49 UTC
Here are two errors I came across that appear when script crashes downloading big files.

Possible solution would be reloading the page if it loads for more than x seconds, because sometimes even when I'm trying to open Figma's web page with a big file in it, it won't load and I need to reload it manually.

```
> Backing up the file(VTB → Design Guidelines 2.0 (Copy))...
        . Setting the download behavior...
	> Saving a local copy of the file(VTB → Design Guidelines 2.0 (Copy))...
		. Opening up the figma command palette...
		. Typing down the download command...
> Stopping the bot...
figma-backup --figma-email "<YOUR_EMAIL>" --figma-password "<YOUR_PASSWORD>"
--figma-token "<YOUR_TOKEN>" --projects-ids "ID1" "ID2" ...

Options:
      --help               Show help                                   [boolean]
      --version            Show version number                         [boolean]
  -e, --figma-email        Figma user's email.               [string] [required]
  -p, --figma-password     Figma user's password.            [string] [required]
  -t, --figma-token        Figma access token.               [string] [required]
      --projects-ids       Figma projects ids.                [array] [required]
      --debug              Opt-in `debug` argument if you want to let the bot to
                           open a local chromium window on your client.
                                                      [boolean] [default: false]
      --download-timeout   This number indicates the maximum amount of time the
                           bot has to wait for a file to be downloaded. (in
                           minutes).                       [number] [default: 5]
      --interaction-delay  This number indicates the delay between interactions.
                           (in seconds).                   [number] [default: 2]
      --typing-delay       This number indicates the delay to type a new
                           character. (in miliseconds).  [number] [default: 100]

BackupError: Backup failed | Protocol error (Input.dispatchKeyEvent): Session closed. Most likely the page has been closed.
    at Bot._backupProjects (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:144:19)
    at async Bot.start (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:166:9)
    at async Object.handler (/usr/local/lib/node_modules/figma-backup/lib/index.js:75:5) {
  _error: Error: Protocol error (Input.dispatchKeyEvent): Session closed. Most likely the page has been closed.
      at CDPSession.send (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/Connection.js:285:35)
      at Keyboard.down (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/Input.js:119:67)
      at Keyboard.press (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/Input.js:235:20)
      at Keyboard.type (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/Input.js:201:28)
      at saveLocalCopy (/usr/local/lib/node_modules/figma-backup/lib/utils/saveLocalCopy.js:30:25)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Bot._backupFile (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:113:9)
      at async Bot._backupProject (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:130:13)
      at async Bot._backupProjects (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:140:17)
      at async Bot.start (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:166:9)
}
```
```
> Backing up the file(00.KP (Components&Guide) (old))...
  ◟     . Waiting for the page to be loaded...> Stopping the bot...
  ◜ 	. Waiting for the page to be loaded...figma-backup --figma-email "<YOUR_EMAIL>" --figma-password "<YOUR_PASSWORD>"
--figma-token "<YOUR_TOKEN>" --projects-ids "ID1" "ID2" ...

Options:
      --help               Show help                                   [boolean]
      --version            Show version number                         [boolean]
  -e, --figma-email        Figma user's email.               [string] [required]
  -p, --figma-password     Figma user's password.            [string] [required]
  -t, --figma-token        Figma access token.               [string] [required]
      --projects-ids       Figma projects ids.                [array] [required]
      --debug              Opt-in `debug` argument if you want to let the bot to
                           open a local chromium window on your client.
                                                      [boolean] [default: false]
      --download-timeout   This number indicates the maximum amount of time the
                           bot has to wait for a file to be downloaded. (in
                           minutes).                       [number] [default: 5]
      --interaction-delay  This number indicates the delay between interactions.
                           (in seconds).                   [number] [default: 2]
      --typing-delay       This number indicates the delay to type a new
                           character. (in miliseconds).  [number] [default: 100]

BackupError: Backup failed | waiting for function failed: timeout 30000ms exceeded
    at Bot._backupProjects (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:144:19)
    at async Bot.start (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:166:9)
    at async Object.handler (/usr/local/lib/node_modules/figma-backup/lib/index.js:75:5) {
  _error: TimeoutError: waiting for function failed: timeout 30000ms exceeded
      at new WaitTask (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:445:34)
      at IsolatedWorld.waitForFunction (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/IsolatedWorld.js:349:26)
      at Frame.waitForFunction (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/Frame.js:479:59)
      at Page.waitForFunction (/usr/local/lib/node_modules/figma-backup/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:2446:33)
      at Bot._backupFile (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:101:20)
      at async Bot._backupProject (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:130:13)
      at async Bot._backupProjects (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:140:17)
      at async Bot.start (/usr/local/lib/node_modules/figma-backup/lib/Bot.js:166:9)
      at async Object.handler (/usr/local/lib/node_modules/figma-backup/lib/index.js:75:5)
}
```

**Comment by mimshins** [comment] 2022-12-28 10:32
@IgorTheOverlord

The second error could be resolved using `--download-timeout` option.
But the first option needs further investigation. Since I can't reproduce the issue It's kinda hard to come up with an optimal solution.

**Comment by IgorLeSouverain** [comment] 2022-12-28 10:36
Second error appeared 2 times in a row while first one is not consistent, restarting the script helped

For tests I can send you a big file ~800Mb, if you want

**Comment by mimshins** [comment] 2022-12-28 10:40
Can you opt-in `--debug` and observe the bot's behavior on the first issue and report back?

Based on the error it throws, this issue is somehow related to the keyboard event. However, this could be due to the page failing to load.

And yes, a large sample file would help me a lot :)

**Comment by mimshins** [comment] 2022-12-28 10:42
> Second error appeared 2 times in a row while first one is not consistent, restarting the script helped

Did you test the process using the `--download-timeout`?

**Comment by IgorLeSouverain** [comment] 2022-12-28 10:45
> > Second error appeared 2 times in a row while first one is not consistent, restarting the script helped
> 
> Did you test the process using the `--download-timeout`?

I tested a couple of times using this flag but I remember it didn't really helped a lot since Figma just won't let you download big files with scripts for some reason, I tried a different script and it was the same

**Comment by IgorLeSouverain** [comment] 2022-12-28 10:46
> Can you opt-in `--debug` and observe the bot's behavior on the first issue and report back?
> 
> Based on the error it throws, this issue is somehow related to the keyboard event. However, this could be due to the page failing to load.
> 
> And yes, a large sample file would help me a lot :)

Debug just opens chromium right? but the thing is I'm using backup server without gui :) 

I'll throw you a file asap

**Comment by mimshins** [comment] 2022-12-28 10:57
But there is one more thing, can you check if you can download the big file manually?

**Comment by IgorLeSouverain** [comment] 2022-12-28 11:00
> But there is one more thing, can you check if you can download the big file manually?

Yes I can

**Comment by IgorLeSouverain** [comment] 2022-12-28 11:51
https://dropmefiles.com/982337 password: 361966
@mimshins 
quote me when done downloading pls

**Comment by mimshins** [comment] 2022-12-28 13:58
> https://dropmefiles.com/982337 password: 361966 @mimshins quote me when done downloading pls

It's done, thanks.

**Comment by IgorLeSouverain** [comment] 2023-01-11 07:40
When first error occurs I think the most simple solution is to just reload the page. Could you just catch BackupError and make a page to reload?

**Comment by IgorLeSouverain** [comment] 2023-01-11 07:44
Wrap all saveLocalCopy.ts into try catch BackupError probably?

**Comment by IgorLeSouverain** [comment] 2023-01-11 07:46
> Wrap all saveLocalCopy.ts into try catch BackupError probably?

Because sometimes it happens after 'Typing down the download command...' and sometimes after 'Executing the download command...'

**Comment by mimshins** [comment] 2023-01-11 08:35
> > Wrap all saveLocalCopy.ts into try catch BackupError probably?
> 
> Because sometimes it happens after 'Typing down the download command...' and sometimes after 'Executing the download command...'

The thing is, reloading the page isn't necessarily a solution for this.
For example, if the error occurs after the `Executing the download command...` message, it is because the download is taking too long (you can fix this by opting in `--download-timeout`) and reloading the page won't fix this issue. (it will make an infinite loop instead)
But if it occurs before this message, it may be because of the page is freezed due to its large size.

**Comment by IgorLeSouverain** [comment] 2023-01-11 09:11
Unfortunately it's not really helping, I set --download-timeout for 15 minutes, it's an overkill but the error appears anyway :(

**Comment by IgorLeSouverain** [comment] 2023-01-11 09:30
When you have time, send me a piece of code to change in your script so a page would reload if it catches BackupError, I'll test it, as I said the error is not consistent, sometimes it appears and sometimes does not, so it won't have infinite loop, let's give it a try

**Comment by mimshins** [comment] 2023-01-14 12:03
@IgorTheOverlord 
I have released a patch(v2.0.2).
Please, upgrade to this version and check if the issue is resolved or not.

**Comment by IgorLeSouverain** [comment] 2023-01-16 11:20
![image](https://user-images.githubusercontent.com/102486458/212665721-7732c9f0-7ea9-44ee-b467-fc49c6baef20.png)
Testing right now, noticed a bug when it says Backup failed even though the file was downloaded and I can open it on figma, the file's size is ~340Mb
Also, is it normal that this message appears everytime?

> (You are seeing this message because the bot has detected network idleness and assumes the download has finished)

And also, --debug works somehow weird, it starts downloading a file, then just skips to the next one after some time saying that it "downloaded" successfully without actually downloading it

**Comment by IgorLeSouverain** [comment] 2023-01-16 11:22
![image](https://user-images.githubusercontent.com/102486458/212666807-54411551-b19e-44d8-861e-cc261cc6b701.png)
After I restarted the bot, it downloaded normally and went for the next file

**Comment by IgorLeSouverain** [comment] 2023-01-16 11:24
> ![image](https://user-images.githubusercontent.com/102486458/212665721-7732c9f0-7ea9-44ee-b467-fc49c6baef20.png) Testing right now, noticed a bug when it says Backup failed even though the file was downloaded and I can open it on figma Also, is it normal that this message appears everytime?
> 
> > (You are seeing this message because the bot has detected network idleness and assumes the download has finished)
> 
> And also, --debug works somehow weird, it starts downloading a file, then just skips to the next one after some time saying that it "downloaded" successfully

Btw, I've waited for more than 1 hour for it to navigate to that file again, but got no results

**Comment by IgorLeSouverain** [comment] 2023-01-16 11:47
![image](https://user-images.githubusercontent.com/102486458/212671207-569585d1-6274-4dc7-9e93-66d170b16017.png)
Another example

**Comment by mimshins** [comment] 2023-01-17 08:51
> ![image](https://user-images.githubusercontent.com/102486458/212665721-7732c9f0-7ea9-44ee-b467-fc49c6baef20.png) Testing right now, noticed a bug when it says Backup failed even though the file was downloaded and I can open it on figma, the file's size is ~340Mb Also, is it normal that this message appears everytime?
> 
> > (You are seeing this message because the bot has detected network idleness and assumes the download has finished)
> 
> And also, --debug works somehow weird, it starts downloading a file, then just skips to the next one after some time saying that it "downloaded" successfully without actually downloading it

The `(You are seeing this message because the bot has detected network idleness and assumes the download has finished)` message is describing the actual behavior of the bot. That's why it sometimes skips the download...
The way I can figure out when a download is finished successfully is to check for Network Idleness. There's no other solution I can think of. However, this approach is kinda bug-prone in large files.

**Comment by mimshins** [comment] 2023-01-17 08:53
The thing is I can't reproduce this on my machine.
I had no problem downloading the sample file you provided for me.

**Comment by IgorLeSouverain** [comment] 2023-01-17 09:28
Okay, I guess we can close the issue, and if I get to resolve the issue by myself I'll write the solution

**Closed as completed** 2023-02-05 12:25 UTC
Labels: enhancement
